name: Build Docker Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: c2sm
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build base image
        if: github.event_name == 'push' && contains(github.event.head_commit.message, 'Dockerfile.base')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: false
          tags: c2sm/extpar-base:latest
          outputs: type=oci,dest=extpar_base_image.tar
          platforms: linux/amd64,linux/arm64

      - name: Build extpar image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.extpar
          push: false
          tags: c2sm/extpar:latest
          outputs: type=oci,dest=extpar_image.tar
          platforms: linux/amd64,linux/arm64

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: extpar_image.tar
          path: extpar_image.tar
