name: Publish docs as release asset

on:
  push:
    tags:
      - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: doc/user_and_implementation_manual
          root_file: user_and_implementation_manual.tex
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs.pdf
          path: doc/user_and_implementation_manual/user_and_implementation_manual.pdf
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} 
          asset_path: doc/user_and_implementation_manual/user_and_implementation_manual.pdf
          asset_name: user_and_implementation_manual.pdf
          asset_content_type: application/pdf
