name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel
        pip install -r requirements.txt

    - name: Build package
      run: |
        python setup.py sdist

    - name: Install package
      run: |
        pip install dist/extpar-*.tar.gz

    - name: Run tests
      run: |
        pytest -v test/pytest/*
