name: Build Base and Extpar images and upload to Docker Hub

on:
  push:
    tags:
      - '*'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Checkout submodules

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: c2sm
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build base image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: c2sm/extpar-base:latest
          platforms: linux/amd64,linux/arm64

      - name: Build extpar image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.extpar
          push: true
          tags: c2sm/extpar:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
