name: Build Base and Extpar images and upload to Docker Hub

on:
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check if branch is whitelisted
        id: branch_check
        run: |
          BRANCH="${GITHUB_REF##*/}"
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          elif grep -Fxq "$BRANCH" .github/branch_whitelist.txt; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

      - name: Build base image
        if: steps.branch_check.outputs.deploy == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          tags: c2sm/extpar-base:latest
          platforms: linux/amd64,linux/arm64

      - name: Build extpar image
        if: steps.branch_check.outputs.deploy == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.extpar
          push: true
          tags: c2sm/extpar:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64